'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Script from 'next/script';
import Link from 'next/link';
import { Camera, Mic, Sparkles, CheckCircle2, Loader2, Lock } from 'lucide-react';
import { Button } from '@/components/ui/button';

declare global {
  interface Window {
    Razorpay: new (options: Record<string, unknown>) => { open: () => void };
  }
}

const FEATURES = [
  { icon: Camera, label: 'Face Scan',        desc: 'AI styling & grooming coaching from your photo' },
  { icon: Mic,    label: 'Voice Check',       desc: 'Scored on clarity, pace & confidence' },
  { icon: '✦',   label: 'Style Profile',     desc: 'Your archetype + ideal look generated by AI' },
  { icon: '◎',   label: 'Date Prep',         desc: 'Outfit, opener & confidence plan for any date' },
  { icon: '◈',   label: 'Roleplay Coach',    desc: 'Practice real conversations, get scored instantly' },
];

interface Props { isFirstTrial: boolean }

export function TrialCheckout({ isFirstTrial }: Props) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function handleStart() {
    setLoading(true);
    setError('');

    try {
      const res = await fetch('/api/payment/create-subscription', { method: 'POST' });
      const data = await res.json() as { subscriptionId?: string; key?: string; error?: string };
      if (!res.ok || !data.subscriptionId) throw new Error(data.error || 'Could not start');

      const rzp = new window.Razorpay({
        key: data.key,
        subscription_id: data.subscriptionId,
        name: 'PresenceAI',
        description: isFirstTrial ? '3 days free · then ₹79/week' : '₹79/week',
        theme: { color: '#7c3aed' },
        handler: async (response: {
          razorpay_payment_id: string;
          razorpay_subscription_id: string;
          razorpay_signature: string;
        }) => {
          const verifyRes = await fetch('/api/payment/verify-subscription', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(response),
          });
          const verifyData = await verifyRes.json() as { success?: boolean; error?: string };
          if (!verifyRes.ok) {
            setError(verifyData.error || 'Verification failed. Try again or contact support.');
            setLoading(false);
            return;
          }
          router.push('/dashboard');
          router.refresh();
        },
        modal: { ondismiss: () => setLoading(false) },
      });
      rzp.open();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong');
      setLoading(false);
    }
  }

  return (
    <>
      <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="lazyOnload" />

      <div className="min-h-screen bg-slate-950 flex flex-col items-center justify-center px-4 py-12">
        <div className="w-full max-w-sm">

          {/* Logo */}
          <div className="text-center mb-10">
            <Link href="/" className="text-2xl font-black gradient-text">PresenceAI</Link>
          </div>

          {isFirstTrial ? (
            <>
              {/* Trial headline */}
              <div className="text-center mb-8">
                <div className="inline-flex items-center gap-2 bg-emerald-900/30 border border-emerald-700/40 rounded-full px-4 py-1.5 text-sm text-emerald-300 mb-5">
                  <Sparkles size={13} /> Free for your first 3 days
                </div>
                <h1 className="text-3xl font-black text-white leading-tight mb-2">
                  Try it free.<br />Fall in love with it.
                </h1>
                <p className="text-slate-400 text-sm">
                  Set up UPI today — no charge for 3 days.<br />
                  Then <span className="text-white font-semibold">₹79/week</span>, cancel anytime.
                </p>
              </div>

              {/* Timeline */}
              <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4 mb-6">
                <div className="flex items-start gap-3 mb-4">
                  <div className="w-6 h-6 rounded-full bg-emerald-600 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-white text-[10px] font-black">✓</span>
                  </div>
                  <div>
                    <p className="text-white text-sm font-semibold">Today — Set up UPI AutoPay</p>
                    <p className="text-slate-500 text-xs">No charge. Mandate authorised.</p>
                  </div>
                </div>
                <div className="flex items-start gap-3 mb-4">
                  <div className="w-6 h-6 rounded-full bg-violet-700/40 border border-violet-600/50 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-violet-300 text-[10px] font-black">3</span>
                  </div>
                  <div>
                    <p className="text-white text-sm font-semibold">Days 1–3 — Full access, free</p>
                    <p className="text-slate-500 text-xs">Use everything. No limits.</p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-6 h-6 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-slate-400 text-[10px] font-black">4</span>
                  </div>
                  <div>
                    <p className="text-slate-300 text-sm font-semibold">Day 4 onwards — ₹79/week</p>
                    <p className="text-slate-500 text-xs">Auto-charges weekly. Cancel anytime.</p>
                  </div>
                </div>
              </div>
            </>
          ) : (
            <>
              {/* Expired headline */}
              <div className="text-center mb-8">
                <div className="inline-flex items-center gap-2 bg-slate-800 border border-slate-700 rounded-full px-4 py-1.5 text-sm text-slate-300 mb-5">
                  <Lock size={13} /> Your trial has ended
                </div>
                <h1 className="text-3xl font-black text-white leading-tight mb-2">
                  Continue your journey
                </h1>
                <p className="text-slate-400 text-sm">
                  <span className="text-white font-semibold">₹79/week</span> — cancel anytime
                </p>
              </div>
            </>
          )}

          {/* Features */}
          <ul className="space-y-2.5 mb-6">
            {FEATURES.map(({ icon: Icon, label, desc }) => (
              <li key={label} className="flex items-center gap-3">
                <CheckCircle2 size={15} className="text-violet-400 shrink-0" />
                <span className="text-white text-sm font-medium">{label}</span>
                <span className="text-slate-600 text-xs hidden sm:block">— {desc}</span>
              </li>
            ))}
          </ul>

          {/* Error */}
          {error && (
            <div className="rounded-xl bg-red-900/20 border border-red-800/30 px-4 py-3 mb-4">
              <p className="text-xs text-red-400">{error}</p>
            </div>
          )}

          {/* CTA */}
          <Button
            onClick={handleStart}
            disabled={loading}
            className="w-full bg-violet-600 hover:bg-violet-500 text-white font-bold text-base h-14 rounded-xl"
          >
            {loading ? (
              <Loader2 size={18} className="animate-spin" />
            ) : isFirstTrial ? (
              'Start free trial →'
            ) : (
              'Subscribe — ₹79/week →'
            )}
          </Button>

          <p className="text-xs text-slate-600 text-center mt-3">
            {isFirstTrial ? 'UPI AutoPay · No charge for 3 days' : 'UPI · Cards · Netbanking'}
            {' '}· Powered by Razorpay
          </p>

          <p className="text-center text-xs text-slate-700 mt-6">
            <a href="mailto:support@mypresence.in" className="hover:text-slate-500 transition-colors">
              support@mypresence.in
            </a>
          </p>
        </div>
      </div>
    </>
  );
}
